// Auto-generated by openapi-typescript
// Run `npm run generate:api` to regenerate from the backend

// Placeholder until types are generated from the backend
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface paths {}

export interface components {
  schemas: Record<string, unknown>;
}
